/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Clan;
import domen.Trening;
import forma.panel.PanelPrikazClanova;
import forma.panel.model.TabelaModelPrikazClan;
import java.util.ArrayList;
import java.util.function.Predicate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import repozitorijum.Kontroler;

/**
 *
 * @author Milan
 */
public class UbaciClanoveUTrening extends javax.swing.JDialog {
    
    private final List<Clan> clanovi;
    private Trening trening;

    /**
     * Creates new form UbaciClanoveUTrening
     */
    public UbaciClanoveUTrening(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        this.clanovi = Kontroler.getInstance().vratiSveClanove();
        initComponents();
        
        postaviPanele();
    }
    
    public UbaciClanoveUTrening(java.awt.Frame parent, boolean modal, Trening trening) throws Exception {
        this(parent, modal);
        this.trening = trening;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtPretraga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ubaci clanove");

        jPanel3.setPreferredSize(new java.awt.Dimension(634, 50));

        jLabel1.setText("Pretrazi: ");

        jTxtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPretragaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPretragaKeyReleased(evt);
            }
        });

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPretragaKeyPressed

    }//GEN-LAST:event_jTxtPretragaKeyPressed

    private void jTxtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPretragaKeyReleased
        Predicate<String> searchedValue = (String v) -> v.toLowerCase().contains(jTxtPretraga.getText());
        List<Clan> kopija = clanovi;
        List<Clan> filteredClanovi = filterList(searchedValue, kopija);
        TabelaModelPrikazClan model = (TabelaModelPrikazClan) panel.getjTable1().getModel();
        //System.out.println("Filtered clanovi size:----" + filteredClanovi.size());
        model.setClanovi(filteredClanovi);
    }//GEN-LAST:event_jTxtPretragaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTable table = panel.getjTable1();
        try {
            int rowSelectedViewModel = table.convertRowIndexToModel(table.getSelectedRow());
            if (rowSelectedViewModel != -1) {
                Clan c = ((TabelaModelPrikazClan) table.getModel()).getClanovi().get(rowSelectedViewModel);
                if (trening.getClanovi().contains(c)) {
                    JOptionPane.showMessageDialog(this, "Član je već prijavljen na trening", "Greška", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        Kontroler.getInstance().ubaciNaTrening(c, trening);
                        
                        JOptionPane.showMessageDialog(this, "Uspešno ste dodali člana na trening(" + trening + ")");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Morate izabrati clana iz tabele!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtPretraga;
    // End of variables declaration//GEN-END:variables
    private PanelPrikazClanova panel;
    
    private void postaviPanele() {
        try {
            
            TabelaModelPrikazClan model = new TabelaModelPrikazClan(clanovi);
            panel = new PanelPrikazClanova(model);
            panel.getHeader().setVisible(false);
            //System.out.println("Clanovi: -------------" + clanovi.size());
            this.add(panel);
            
            pack();
        } catch (Exception ex) {
            Logger.getLogger(UbaciClanoveUTrening.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public List<Clan> filterList(Predicate<String> p, List<Clan> clanovi) {
        List<Clan> result = new ArrayList<>();
        for (Clan clan : clanovi) {
            if (p.test(clan.getAttributes())) {
                result.add(clan);
            }
        }
        return result;
    }
}
