/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Sport;
import domen.Trener;
import domen.Trening;
import java.awt.Insets;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import request.RequestObject;
import response.ResponseObject;
import status.EnumResponseStatus;
import util.Akcije;

/**
 *
 * @author Milan
 */
public class UnosTreninga extends javax.swing.JDialog {

    /**
     * Creates new form UnosTreninga
     */
    public UnosTreninga(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        datum = LocalDate.now();
        vremeOd = LocalTime.of(10, 0);
        vremeDo = LocalTime.of(11, 0);
        srediFormu();
        popuniCombo();
    }
    private LocalDate datum;
    private LocalTime vremeOd;
    private LocalTime vremeDo;
    private List<Trener> treneri;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnVremePocetkaPP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtDatum = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jbtnVremePocetkaMM = new javax.swing.JButton();
        jbtnVremeKrajaMM = new javax.swing.JButton();
        jtxtVremeKraja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnVremeKrajaPP = new javax.swing.JButton();
        jtxtVremePocetka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSviTreneri = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOdabraniTreneri = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos novog treninga");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Postavi datum i vreme", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jbtnVremePocetkaPP.setText("+30");
        jbtnVremePocetkaPP.setToolTipText("dodaj 30 minuta");
        jbtnVremePocetkaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVremePocetkaPPActionPerformed(evt);
            }
        });

        jLabel2.setText("Vreme pocetka");

        jButton3.setText("S");
        jButton3.setToolTipText("Sledeci dan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbtnVremePocetkaMM.setText("-30");
        jbtnVremePocetkaMM.setToolTipText("oduzmi 30 minuta");
        jbtnVremePocetkaMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVremePocetkaMMActionPerformed(evt);
            }
        });

        jbtnVremeKrajaMM.setText("-30");
        jbtnVremeKrajaMM.setToolTipText("oduzmi 30 minuta");
        jbtnVremeKrajaMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVremeKrajaMMActionPerformed(evt);
            }
        });

        jLabel3.setText("Vreme kraja");

        jbtnVremeKrajaPP.setText("+30");
        jbtnVremeKrajaPP.setToolTipText("dodaj 30 minuta");
        jbtnVremeKrajaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVremeKrajaPPActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtVremeKraja)
                    .addComponent(jtxtVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnVremePocetkaMM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnVremePocetkaPP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnVremeKrajaMM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnVremeKrajaPP)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton3)
                    .addComponent(jtxtVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVremePocetkaPP)
                    .addComponent(jbtnVremePocetkaMM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtVremeKraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVremeKrajaPP)
                    .addComponent(jbtnVremeKrajaMM))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izaberi sport i trenera (nije obavezno)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListSviTreneri);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Sport");

        jScrollPane2.setViewportView(jListOdabraniTreneri);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jButton4.setText("Sacuvaj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        datum = datum.plusDays(1);
        srediFormu();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnVremePocetkaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVremePocetkaPPActionPerformed
        vremeOd = vremeOd.plusMinutes(30);
        srediFormu();
    }//GEN-LAST:event_jbtnVremePocetkaPPActionPerformed

    private void jbtnVremeKrajaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVremeKrajaPPActionPerformed
        vremeDo = vremeDo.plusMinutes(30);
        srediFormu();
    }//GEN-LAST:event_jbtnVremeKrajaPPActionPerformed

    private void jbtnVremePocetkaMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVremePocetkaMMActionPerformed
        vremeOd = vremeOd.minusMinutes(30);
        srediFormu();
    }//GEN-LAST:event_jbtnVremePocetkaMMActionPerformed

    private void jbtnVremeKrajaMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVremeKrajaMMActionPerformed
        vremeDo = vremeDo.minusMinutes(30);
        srediFormu();
    }//GEN-LAST:event_jbtnVremeKrajaMMActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (treneri != null) {
            treneri.stream()
                    .filter(t -> t.getSport().equals(jComboBox1.getSelectedItem()))
                    .forEach(t -> ((DefaultListModel) jListSviTreneri.getModel()).addElement(t));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jListSviTreneri.getSelectedValuesList()
                .forEach(s -> {
                    ((DefaultListModel) jListOdabraniTreneri.getModel()).addElement(s);
                    ((DefaultListModel) jListSviTreneri.getModel()).removeElement(s);
                });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jListOdabraniTreneri.getSelectedValuesList()
                .forEach(s -> {
                    ((DefaultListModel) jListSviTreneri.getModel()).addElement(s);
                    ((DefaultListModel) jListOdabraniTreneri.getModel()).removeElement(s);
                });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String dat = datum.format(DateTimeFormatter.ISO_DATE);
            datum = LocalDate.parse(dat,DateTimeFormatter.ISO_DATE);

            vremeOd = LocalTime.parse(jtxtVremePocetka.getText().trim(), DateTimeFormatter.ISO_TIME);
            vremeDo = LocalTime.parse(jtxtVremeKraja.getText().trim(), DateTimeFormatter.ISO_TIME);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pogresan format datuma");
            return;
        }
        Trening t= new Trening(vremeOd, vremeDo, datum);
        List<Trener> odabraniTreneri = new ArrayList<>();
        DefaultListModel m = (DefaultListModel) jListOdabraniTreneri.getModel();
        
        for(int i = 0; i< m.getSize();i++){
            odabraniTreneri.add((Trener) m.getElementAt(i));
        }
        
        if(!odabraniTreneri.isEmpty()){
            t.setTreneri(odabraniTreneri);
        }
        try {
            Komunikacija.vratiInstancu().posaljiZahtev(new RequestObject(t, Akcije.KREIRAJ_TRENING));
            
            ResponseObject res = Komunikacija.vratiInstancu().procitajOdgovor();
            
            if (res.getStatus() == EnumResponseStatus.ERROR) {
                JOptionPane.showMessageDialog(this, res.getMessage());
                return;
            }
            JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali trening");
        } catch (IOException ex) {
            Logger.getLogger(UnosTreninga.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UnosTreninga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<Sport> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Trener> jListOdabraniTreneri;
    private javax.swing.JList<Trener> jListSviTreneri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnVremeKrajaMM;
    private javax.swing.JButton jbtnVremeKrajaPP;
    private javax.swing.JButton jbtnVremePocetkaMM;
    private javax.swing.JButton jbtnVremePocetkaPP;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtVremeKraja;
    private javax.swing.JTextField jtxtVremePocetka;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jtxtDatum.setText(datum.format(DateTimeFormatter.ofPattern("dd.MM.yyyy - EEEE", new Locale("sr", "RS"))));
        jtxtVremePocetka.setText(vremeOd.format(DateTimeFormatter.ISO_TIME));
        jtxtVremeKraja.setText(vremeDo.format(DateTimeFormatter.ISO_TIME));
    }

    private void popuniCombo() throws Exception {
        try {
            RequestObject req = new RequestObject();
            req.setAction(Akcije.VRATI_SVA_SPORTOVE);

            Komunikacija.vratiInstancu().posaljiZahtev(req);

            ResponseObject res = Komunikacija.vratiInstancu().procitajOdgovor();

            if (res.getObject() instanceof List) {
                List<Sport> sportovi = (List<Sport>) res.getObject();
                sportovi.forEach(s -> jComboBox1.addItem(s));

            }
            RequestObject req1 = new RequestObject();
            req1.setAction(Akcije.VRATI_SVE_TRENERE);

            Komunikacija.vratiInstancu().posaljiZahtev(req1);

            res = Komunikacija.vratiInstancu().procitajOdgovor();

            if (res.getObject() instanceof List) {
                treneri = (List<Trener>) res.getObject();
            }
            jListOdabraniTreneri.setModel(new DefaultListModel<>());
            jListSviTreneri.setModel(new DefaultListModel<>());
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
            throw new Exception("Greska prilikom popunjavanja forme od strane servera.");
        }
    }

}
