/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.panel;

import domen.Clan;
import domen.Sport;
import domen.Trener;
import domen.Trening;
import forme.INazad;
import forme.UbaciClanoveNaTrening;
import forme.UbaciTrenereNaTrening;
import forme.UnosTreninga;
import forme.panel.model.ListModelClanovi;
import forme.panel.model.ListModelTrener;
import forme.panel.model.TabelaModelPrikazTrener;
import forme.panel.model.TableModelPrikazVreme;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import javax.swing.JList;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;
import komunikacija.Komunikacija;
import radnaMemorija.Memory;
import request.RequestObject;
import response.ResponseObject;
import status.EnumResponseStatus;
import util.Akcije;

/**
 *
 * @author Milan
 */
public class PanelZaPrikazTreninga extends javax.swing.JPanel implements INazad {

    private List<Trening> treninzi;

    /**
     * Creates new form PanelZaPrikazTreninga
     */
    public PanelZaPrikazTreninga() throws Exception {
        initComponents();
        ucitajListuTreninga();
        jProgressBarPopunjenostTreninga.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Centralni = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jcboxDatumTreninga = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePrikazVremena = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTrener = new javax.swing.JList<>();
        jBtnDodajTreneraNaTrening = new javax.swing.JButton();
        jBtnObrisiTreneraSaTreninga = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClanova = new javax.swing.JList<>();
        jBtnDodajClanaNaTrening = new javax.swing.JButton();
        jBtnObrisiClanaSaTreninga = new javax.swing.JButton();
        jProgressBarPopunjenostTreninga = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtSport1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtMaxBr = new javax.swing.JTextField();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnDodajTrening = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(772, 700));

        Centralni.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 73));

        jcboxDatumTreninga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcboxDatumTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxDatumTreningaActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum treninga: ");

        jTablePrikazVremena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePrikazVremena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vreme od", "Vreme do"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrikazVremena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrikazVremenaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePrikazVremena);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jcboxDatumTreninga, javax.swing.GroupLayout.Alignment.LEADING, 0, 218, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxDatumTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        Centralni.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setPreferredSize(new java.awt.Dimension(1378, 456));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Treneri"));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(475, 130));

        jListTrener.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(jListTrener);

        jBtnDodajTreneraNaTrening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/rsz_greenadd.png"))); // NOI18N
        jBtnDodajTreneraNaTrening.setToolTipText("dodaj clana");
        jBtnDodajTreneraNaTrening.setPreferredSize(new java.awt.Dimension(28, 27));
        jBtnDodajTreneraNaTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajTreneraNaTreningActionPerformed(evt);
            }
        });

        jBtnObrisiTreneraSaTreninga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/rsz_minus.png"))); // NOI18N
        jBtnObrisiTreneraSaTreninga.setToolTipText("obrisi trenera sa treninga");
        jBtnObrisiTreneraSaTreninga.setPreferredSize(new java.awt.Dimension(28, 27));
        jBtnObrisiTreneraSaTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiTreneraSaTreningaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajTreneraNaTrening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObrisiTreneraSaTreninga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnDodajTreneraNaTrening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnObrisiTreneraSaTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clanovi"));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(475, 130));

        jListClanova.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jListClanova.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane1.setViewportView(jListClanova);

        jBtnDodajClanaNaTrening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/rsz_greenadd.png"))); // NOI18N
        jBtnDodajClanaNaTrening.setToolTipText("dodaj clana");
        jBtnDodajClanaNaTrening.setPreferredSize(new java.awt.Dimension(28, 27));
        jBtnDodajClanaNaTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajClanaNaTreningActionPerformed(evt);
            }
        });

        jBtnObrisiClanaSaTreninga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/rsz_minus.png"))); // NOI18N
        jBtnObrisiClanaSaTreninga.setToolTipText("obrisi clana sa treninga");
        jBtnObrisiClanaSaTreninga.setPreferredSize(new java.awt.Dimension(28, 27));
        jBtnObrisiClanaSaTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiClanaSaTreningaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajClanaNaTrening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObrisiClanaSaTreninga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnDodajClanaNaTrening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnObrisiClanaSaTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jProgressBarPopunjenostTreninga.setToolTipText("Procenat popunjenosti treninga");
        jProgressBarPopunjenostTreninga.setMinimumSize(new java.awt.Dimension(146, 17));
        jProgressBarPopunjenostTreninga.setName("Popunjenost treninga"); // NOI18N
        jProgressBarPopunjenostTreninga.setOpaque(true);
        jProgressBarPopunjenostTreninga.setStringPainted(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sport: ");
        jPanel6.add(jLabel4);

        jtxtSport1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jtxtSport1.setEnabled(false);
        jtxtSport1.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel6.add(jtxtSport1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Maksimum članova: ");
        jPanel6.add(jLabel5);

        jtxtMaxBr.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtMaxBr.setEnabled(false);
        jtxtMaxBr.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel6.add(jtxtMaxBr);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarPopunjenostTreninga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarPopunjenostTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        Centralni.add(jPanel4, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Prikaz treninga");

        jbtnDodajTrening.setText("Dodaj trening");
        jbtnDodajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajTreningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDodajTrening)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jbtnDodajTrening)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Centralni, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Centralni, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jcboxDatumTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxDatumTreningaActionPerformed

//        try {
//            RequestObject requestObj = new RequestObject();
//            requestObj.setObject((LocalDate) jcboxDatumTreninga.getSelectedItem());
//            requestObj.setAction(Akcije.VRATI_VREMENA);
//            Komunikacija.vratiInstancu().posaljiZahtev(requestObj);
        LocalDate datum = (LocalDate) jcboxDatumTreninga.getSelectedItem();

        List<Trening> tr = treninzi.stream()
                .filter(t -> t.getDatum().equals(datum))
                .collect(Collectors.toList());
//            ResponseObject response = Komunikacija.vratiInstancu().procitajOdgovor();
//            treninzi = (List<Trening>) response.getObject();
        popuniTabeluVremena(tr);

//        } catch (IOException | ClassNotFoundException ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_jcboxDatumTreningaActionPerformed

    private void jTablePrikazVremenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrikazVremenaMouseClicked
        int selectedRow = jTablePrikazVremena.convertRowIndexToView(jTablePrikazVremena.getSelectedRow());

        if (selectedRow != -1) {
            jProgressBarPopunjenostTreninga.setVisible(true);
            Trening trening = ((TableModelPrikazVreme) jTablePrikazVremena.getModel()).vratiTreninge().get(selectedRow);
            Memory.getInstance().setTrening(trening);
            List<Trener> treneri;
            treneri = trening.getTreneri().stream().distinct().collect(Collectors.toList());
            List<Clan> clanovi = trening.getClanovi();

//            try {
//                RequestObject requestObj = new RequestObject();
//
//                requestObj.setAction(Akcije.VRATI_SVE_TRENERE_ZA_TRENING);
//                requestObj.setObject(trening);
//                Komunikacija.vratiInstancu().posaljiZahtev(requestObj);
//
//                ResponseObject responseObj = Komunikacija.vratiInstancu().procitajOdgovor();
//                treneri = (List<Trener>) responseObj.getObject();
//
//                trening.setTreneri(treneri);
//            } catch (IOException | ClassNotFoundException ex) {
//                JOptionPane.showMessageDialog(this, ex.getMessage() + "\nGreška prilikom ušitavanja trenera.", "Ušitavanje trenera", JOptionPane.ERROR_MESSAGE);
//            }
//            try {
//                RequestObject requestObj = new RequestObject();
//
//                requestObj.setAction(Akcije.VRATI_SVE_CLANOVE_ZA_TRENING);
//                requestObj.setObject(trening);
//                Komunikacija.vratiInstancu().posaljiZahtev(requestObj);
//
//                ResponseObject responseObj = Komunikacija.vratiInstancu().procitajOdgovor();
//
//                clanovi = (List<Clan>) responseObj.getObject();
//
//                trening.setClanovi(clanovi);
//            } catch (IOException | ClassNotFoundException ex) {
//                JOptionPane.showMessageDialog(this, ex.getMessage() + "\nGreška prilikom učitavanja članova.", "Učitavanje članova", JOptionPane.ERROR_MESSAGE);
//            }
            try {
                jListTrener.setModel(new ListModelTrener(treneri));
                jListClanova.setModel(new ListModelClanovi(clanovi));

                refresh();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }

            if (!treneri.isEmpty()) {
                Sport s = treneri.get(0).getSport();
                jtxtSport1.setText(s.getNaziv());
                jtxtMaxBr.setText("" + s.getMaxBrClanova());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati vreme treninga!", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jTablePrikazVremenaMouseClicked

    private void jBtnDodajClanaNaTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajClanaNaTreningActionPerformed
        try {
            Trening trening = (Trening) Memory.getInstance().getTrening();
            //trening.setClanovi(((ListModelClanovi) jListClanova.getModel()).vratiClanoveNaTreningu());
            UbaciClanoveNaTrening dialog = new UbaciClanoveNaTrening(null, false, trening, this);
            dialog.setLocation(jBtnDodajClanaNaTrening.getLocation());
            dialog.setVisible(true);
            refresh();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Morate izabrati vreme treninga!", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnDodajClanaNaTreningActionPerformed

    private void jBtnDodajTreneraNaTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajTreneraNaTreningActionPerformed
        try {
            Trening trening = (Trening) Memory.getInstance().getTrening();
            trening.setTreneri(((ListModelTrener) jListTrener.getModel()).vratiTrenereNaTreningu());
            UbaciTrenereNaTrening dialog = new UbaciTrenereNaTrening(null, false, trening);
            dialog.setLocation(jBtnDodajClanaNaTrening.getLocation());
            dialog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Morate izabrati vreme treninga!", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnDodajTreneraNaTreningActionPerformed

    private void jbtnDodajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajTreningActionPerformed
        try {

            UnosTreninga form = new UnosTreninga(null, true);
            form.setVisible(true);
            ucitajListuTreninga();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnDodajTreningActionPerformed

    private void jBtnObrisiClanaSaTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiClanaSaTreningaActionPerformed

        int odg = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete selektovane članove sa treninga?", JOptionPane.OPTION_TYPE_PROPERTY, JOptionPane.YES_NO_OPTION);
        if (odg == JOptionPane.YES_OPTION) {
            try {
                List<Object> pom = new ArrayList<>();
                List<Clan> clanovi = jListClanova.getSelectedValuesList();
                pom.add(clanovi);
                pom.add(Memory.getInstance().getTrening());
                RequestObject req = new RequestObject();
                req.setObject(pom);
                req.setAction(Akcije.OBRISI_CLANOVE_SA_TRENINGA);

                Komunikacija.vratiInstancu().posaljiZahtev(req);

                ResponseObject res = Komunikacija.vratiInstancu().procitajOdgovor();

                if (res.getStatus() == EnumResponseStatus.ERROR) {
                    JOptionPane.showMessageDialog(this, res.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                ((ListModelClanovi) jListClanova.getModel()).obrisi(clanovi);
                refresh();
                JOptionPane.showMessageDialog(this, res.getMessage(), "Uspešna akcija", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnObrisiClanaSaTreningaActionPerformed

    private void jBtnObrisiTreneraSaTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiTreneraSaTreningaActionPerformed

        int odg = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete selektovane trenere sa treninga?", JOptionPane.OPTION_TYPE_PROPERTY, JOptionPane.YES_NO_OPTION);
        if (odg == JOptionPane.YES_OPTION) {
            try {
                List<Object> pom = new ArrayList<>();
                List<Trener> treneri = jListTrener.getSelectedValuesList();
                pom.add(treneri);
                pom.add(Memory.getInstance().getTrening());
                RequestObject req = new RequestObject();
                req.setObject(pom);
                req.setAction(Akcije.OBRISI_TRENERE_SA_TRENINGA);

                Komunikacija.vratiInstancu().posaljiZahtev(req);

                ResponseObject res = Komunikacija.vratiInstancu().procitajOdgovor();

                if (res.getStatus() == EnumResponseStatus.ERROR) {
                    JOptionPane.showMessageDialog(this, res.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                ((ListModelTrener) jListTrener.getModel()).obrisi(treneri);
                refresh();
                JOptionPane.showMessageDialog(this, res.getMessage(), "Uspešna akcija", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnObrisiTreneraSaTreningaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centralni;
    private javax.swing.JButton jBtnDodajClanaNaTrening;
    private javax.swing.JButton jBtnDodajTreneraNaTrening;
    private javax.swing.JButton jBtnObrisiClanaSaTreninga;
    private javax.swing.JButton jBtnObrisiTreneraSaTreninga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Clan> jListClanova;
    private javax.swing.JList<Trener> jListTrener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JProgressBar jProgressBarPopunjenostTreninga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePrikazVremena;
    private javax.swing.JButton jbtnDodajTrening;
    private javax.swing.JComboBox<LocalDate> jcboxDatumTreninga;
    private javax.swing.JTextField jtxtMaxBr;
    private javax.swing.JTextField jtxtSport1;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluVremena(List<Trening> treninzi) {
        TableModelPrikazVreme model = new TableModelPrikazVreme(treninzi);

        jTablePrikazVremena.setModel(model);
        // model.fireTableDataChanged();
    }

    private void ucitajListuTreninga() throws Exception {
        jcboxDatumTreninga.removeAllItems();
        try {
            RequestObject requestObj = new RequestObject();

            requestObj.setAction(Akcije.VRATI_TRENINGE);
            Komunikacija.vratiInstancu().posaljiZahtev(requestObj);

            ResponseObject responseObj = Komunikacija.vratiInstancu().procitajOdgovor();
            treninzi = (List<Trening>) responseObj.getObject();

            List<LocalDate> datumi = new ArrayList<>();

            for (Trening trening : treninzi) {
                if (!datumi.contains(trening.getDatum())) {
                    datumi.add(trening.getDatum());
                }
            }

            datumi.stream().forEach((da) -> {
                jcboxDatumTreninga.addItem(da);
            });

        } catch (IOException | ClassNotFoundException ex) {
            //ex.printStackTrace();
            throw new Exception(ex + "\nNe može se prikazati panel sa treninzima!");
        }
    }

    @Override
    public boolean proveriIzmene() {
        return true;
    }

    public void refresh() {
        if (!Memory.getInstance().getTrening().getClanovi().isEmpty() && !Memory.getInstance().getTrening().getTreneri().isEmpty()) {
            int popunjenost = new BigDecimal((Memory.getInstance().getTrening().getClanovi().size() * 100.0) / Memory.getInstance().getTrening().getTreneri().get(0).getSport().getMaxBrClanova()).setScale(0, RoundingMode.HALF_UP).intValue();
            jProgressBarPopunjenostTreninga.setValue(popunjenost);
        } else {
            jProgressBarPopunjenostTreninga.setValue(0);
        }
    }

    public JList<Clan> getjListClanova() {
        return jListClanova;
    }

    public void setjListClanova(JList<Clan> jListClanova) {
        this.jListClanova = jListClanova;
    }

    public JList<Trener> getjListTrener() {
        return jListTrener;
    }

    public void setjListTrener(JList<Trener> jListTrener) {
        this.jListTrener = jListTrener;
    }

    
}
